
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ev_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ev_pipeline'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  ev_pipeline:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: STAGING_EV
    curated:
      +materialized: table
      +schema: CURATED_EV
    analytics:
      +materialized: table
      +schema: ANALYTICS_EV

seeds:
  ev_pipeline:
    afdc_registrations:
      +schema: RAW_EV
    dim_states:
      +schema: RAW_EV
      +column_types:
        state_fips: varchar(2)
        state_name: varchar
        state_abbr: varchar(2)
